<div wire:loading>
    <svg wire:loading.class="animate-spin" class="  h-10 w-10 stroke-red-400" xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink" width="200px" height="200px" viewBox="0 0 100 100"
        preserveAspectRatio="xMidYMid">
        <circle cx="50" cy="50" r="32" stroke-width="9"
            stroke-dasharray="50.26548245743669 50.26548245743669" fill="none" stroke-linecap="round"
            transform="matrix(1,0,0,1,0,0)" style="animation-play-state:paused"></circle>
        <!-- generated by https://loading.io/ -->
    </svg>
</div>