<div class="mt-12 p-3 md:p-8 lg:p-10 bg-white dark:bg-slate-600 rounded-xl shadow h-fit md:w-[600px] lg:w-[800px] xl:w-[1000px] ">
    @if(session()->has('message_validation'))
    <div class="flex flex-col gap-y-5 items-center">
        <div class="flex text-green-500 gap-x-2">
            <span><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 12.75l6 6 9-13.5" />
            </svg>
            </span>
            <p>{{ session('message_validation') }}</p>
        </div>
        <form wire:submit.prevent="reload">
            <div>
                <x-buttons.validation>
                    <p>New Post</p>
                </x-buttons.validation>
            </div>
        </form>
    </div>
    @else
    <div>
        <h3 class="text-red-400 text-lg font-semibold pb-2 pl-2 lg:pb-4">New Post</h3>
        <form wire:submit.prevent="upload" class="flex flex-col">
            @csrf
            <div class=" @if(!$image) border-2 @endif rounded-xl border-gray-300 relative">
                <div class="rounded-xl overflow-hidden min-h-[300px] max-h-[50vh] w-fit mx-auto">
                    @if ($image)
                        <img wire:loading.class="hidden" wire:target="image" class="object-scale-down  min-h-[300px] max-h-[50vh] w-full rounded-xl " src="{{ $image->temporaryUrl() }}">
                    @endif
                </div>
                <div class="absolute bottom-0 left-0" wire:loading wire:target="image">
                    <svg class=" animate-spin h-10 w-10 stroke-red-400" xmlns="http://www.w3.org/2000/svg"
                        xmlns:xlink="http://www.w3.org/1999/xlink" width="200px" height="200px" viewBox="0 0 100 100"
                        preserveAspectRatio="xMidYMid">
                        <circle cx="50" cy="50" r="32" stroke-width="9"
                            stroke-dasharray="50.26548245743669 50.26548245743669" fill="none" stroke-linecap="round"
                            transform="matrix(1,0,0,1,0,0)" style="animation-play-state:paused"></circle>
                        <!-- generated by https://loading.io/ -->
                    </svg>
                </div>
                <label class=" absolute top-0 left-0 bottom-0 right-0 cursor-pointer flex justify-center items-center text-lg font-semibold text-gray-600 hover:text-gray-400 duration-300" for="image">@if(!$image)Click me @endif</label>
                <input class="hidden" type="file" name="image" id="image" wire:model="image">
            </div>
            @error('image')
                <x-errors.form_error :message="$message"/>
            @enderror
            <div class="px-3 py-5">
                <x-inputs.text name="description" type="text" label="Enter an image description" placeholder="Enter a description" value="" wire:model="description"/>
            </div>
            <div class="mx-auto fit-content p-5">
                <x-buttons.validation>
                    <p>Upload Image</p>
                </x-buttons.validation>
            </div>
        </form>
    </div>
    @endif
</div>
